version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    mem_limit: 128M
    container_name: 02_NginxProxyManager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLLITE_FILE: "/docker/02_NginxProxyManager/data/npm.sqlite"
    volumes:
      - /docker/02_NginxProxyManager/data:/data
      - /docker/02_NginxProxyManager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: curl --fail http://10.1.0.57:81 || exit 1        #   Please Enter your local IP.
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s