version: "3"
services:
  watchtower:
    container_name: 06_WatchTower
    mem_limit: 128M
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 1 * *
      TZ: Europe/Berlin
    restart: always